# Generated by Django 4.0.5 on 2022-06-03 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meta_class', '0002_alter_cidade_id_alter_pessoa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='cidade',
            table='contact_users',
        ),
    ]
