# Generated by Django 4.0.5 on 2022-06-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_class', '0003_alter_cidade_id_alter_cidade_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cidade',
            table='contact_city',
        ),
        migrations.AlterModelTable(
            name='pessoa',
            table='contact_user',
        ),
    ]
